apiVersion: apps/v1
kind: Deployment
metadata:
  name: veena-deployment
  labels:
    app: docker-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-project
  template:
    metadata:
      labels:
        app: docker-project
    spec:
      containers:
      - name: veena
        image: veena9999/dockerrepo1
        ports:
        - containerPort: 8000