apiVersion: v1
kind: Service
metadata:
  name: veena-service
spec:
  type: NodePort
  selector:
    app: docker-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31267